# ssh access The authenticity of host
# Are you sure you want to continue connecting (yes/no)?
# automation input 'yes'

---
- hosts:  all
  connection: local
  serial: 1 #여러 호스트를 동시에 처리하지 않고 한 호스트 씩 처리
  gather_facts: no
  become: yes

  tasks:
    - name: input known_hosts using ssh-keyscan 
      command: "ssh-keygen -N '' -f ~/.ssh/id_rsa"
      igmore_errors: yes
      run_once: true
      
    - name: import id_rsa.pub
      connection: local
      command: "cat /home/
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: "{{ user_name }}", admin
        append: yes
        createhome: yes
        home: /home/"{{ user_name }}"
        state: present
        
    - name: allow ubuntu user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: "{{ user_name }}   ALL=(ALL:ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'
        state: present

    - name: set up authorized keys for the user
      authorized_key: user="{{ user_name }}" key="{{item}}"
      with_file:
      - ~/.ssh/id_rsa.pub

# 변수정의
  vars:
    user_name: ubuntu
    user_password: qwer1234
    
     
