# ssh access The authenticity of host
# Are you sure you want to continue connecting (yes/no)?
# automation input 'yes'

---
- hosts:  all        # /etc/ansible/hosts에 nodes에 대한 정보를 읽어들여서 nodes에서 실행하는 것이 아니라
  connection: local  # 목적지를 local(ansible-server)로 잡아서 실행 
  serial: 1          #여러 호스트를 동시에 처리하지 않고 한 호스트 씩 처리 성능이 좋은 시스템의 경우 빠른 진행으로 겹치는 경우가 발생하므로 설정한 옵션
  gather_facts: no
  become: yes

  tasks:
    - name: input known_hosts using ssh-keyscan 
      command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }} # "{{ ansible_host }}"라는 변수에 nodes를 불러와
      register: keyscan #command로 확인된 node의 키 값을 변수 keyscan 에 저장
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        line: {{ item }} #kryscan 변수에 있는 값이 stdout_lines으로 출력되면 known_hosts 파일에 한 줄씩 작성
        with_items:
        - "{{ keyscan.stdout_lines }}"
