# ssh access The authenticity of host
# Are you sure you want to continue connecting (yes/no)?
# automation input 'yes'

---
- hosts: all
  connection: local
  serial: 1
  gather_facts: no

  tasks:
    - name: input known_hosts using ssh-keyscan
      command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }} # "{{ ansible_host }}"라는 변수에 nodes를 불러와
      register: keyscan #command로 확인된 node의 키 값을 변수 keyscan 에 저장

    - lineinfile:
        dest: ~/.ssh/known_hosts
        line: "{{ item }}" #kryscan 변수에 있는 값이 stdout_lines으로 출력되면 known_hosts 파일에 한 줄씩 작성
        create: yes
      with_items:
        - "{{ keyscan.stdout_lines }}"

