# ssh access The authenticity of host
# Are you sure you want to continue connecting (yes/no)?
# automation input 'yes'

---
- hosts:  all
  connection: local
  serial: 1 #여러 호스트를 동시에 처리하지 않고 한 호스트 씩 처리
  gather_facts: no
  become: yes

  tasks:
    - name: input known_hosts using ssh-keyscan 
      command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
      register: keyscan #command로 확인된 node의 키 값을 변수 keyscan에 저장
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        line: {{ item }} #kryscan 변수에 있는 값이 stdout_lines으로 출력되면 known_hosts 파일에 한 줄씩 작성
        with_file:
        - "{{ keyscan.stdout_lines }}"
