# configure the worker nodes and initialize the cluster
#This playbook contains the instructions that have to be executed on worker nodes.
#With the second replay, a single task executes the join command on all worker nodes.
#At the end of this activity, the two worker nodes will be part of the cluster.
#Save and close the file when done and run the playbook by running locally
# : ansible-playbook -i hosts workers.yml

---
- hosts: master
  become: yes
  gather_facts: false

  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"



- hosts: workers
  become: yes

  tasks:
    - name: remove swap [swapoff -a] (Master and worker nodes work the same)
      shell: "swapoff -a"
    - name: remove swap fstab (Master and worker nodes work the same)
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: join cluster	
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
